### ISSUE TITLE
[Ziggo] Unexpected Error: MissingSchema, not able to log in

### ISSUE THREAD

**Issue by tke-tke** [dut-iptv/dut-iptv.github.io#51] opened 2020-12-26 18:19 UTC
Error after Fresh install of LibreELEC (9.2.6 Kodi 18.9) on a RPi 4B with only this plugin added.
Installation went fine, all dependencies seem to have installed correctly.

Not able to log into Ziggo Go -> Ziggo Go Unexpected error MissingSchema. Perhaps you meant http://?
In kodi.log this is logged:

2020-12-26 15:33:21.456 T:2794333040   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.MissingSchema'>
                                            Error Contents: Invalid URL '': No schema supplied. Perhaps you meant http://?
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.ziggo/service.py", line 2, in <module>
                                                main()
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/l5/service.py", line 62, in main
                                                startup()
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/l5/service.py", line 50, in startup
                                                hourly(type=0)
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/l5/service.py", line 19, in hourly
                                                api_get_session()
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/api.py", line 127, in api_get_session
                                                download = api_download(url=devices_url, type='get', headers=api_get_headers(), data=None, json_data=False, return_json=True)
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/l5/api.py", line 17, in api_download
                                                resp = getattr(session, type)(url, allow_redirects=allow_redirects, auth=auth)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 546, in get
                                                return self.request('GET', url, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/l4/session.py", line 52, in request
                                                data = super(Session, self).request(method, url, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 519, in request
                                                prep = self.prepare_request(req)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 462, in prepare_request
                                                hooks=merge_hooks(request.hooks, self.hooks),
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 313, in prepare
                                                self.prepare_url(url, params)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 387, in prepare_url
                                                raise MissingSchema(error)
                                            MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
                                            -->End of Python script error report<--
											
											Please advice how to resolve this.
thanks!

**Comment by pontedennis** [comment] 2020-12-27 09:00
Yes i have the same problem

**Comment by tke-tke** [comment] 2020-12-27 13:28
Beta Version 0.9.115 seems to be ok

 

Van: pontedennis [mailto:notifications@github.com] 
Verzonden: Sunday, December 27, 2020 10:01 AM
Aan: dut-iptv/dut-iptv.github.io
CC: tke-tke; Author
Onderwerp: Re: [dut-iptv/dut-iptv.github.io] Ziggo GO - Unexpected Error: MissingSchema, not able to log in (#51)

 

Yes i have the same problem

**Comment by pontedennis** [comment] 2020-12-27 13:47
How to get the Beta Version 0.9.115?Verzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: tke-tke <notifications@github.com> Datum: 27-12-2020  14:28  (GMT+01:00) Aan: "dut-iptv/dut-iptv.github.io" <dut-iptv.github.io@noreply.github.com> Cc: pontedennis <pontedennis@gmail.com>, Comment <comment@noreply.github.com> Onderwerp: Re: [dut-iptv/dut-iptv.github.io] Ziggo GO  - Unexpected Error: MissingSchema, not able to log in (#51) 

Beta Version 0.9.115 seems to be ok



 



Van: pontedennis [mailto:notifications@github.com] 

Verzonden: Sunday, December 27, 2020 10:01 AM

Aan: dut-iptv/dut-iptv.github.io

CC: tke-tke; Author

Onderwerp: Re: [dut-iptv/dut-iptv.github.io] Ziggo GO - Unexpected Error: MissingSchema, not able to log in (#51)



 



Yes i have the same problem

**Comment by tke-tke** [comment] 2020-12-27 15:17
Goto

https://github.com/bluhb/dut-iptv.github.io/blob/master/beta/leia/plugin.video.ziggo/plugin.video.ziggo-0.9.115.zip

 

and choose button ->download ( about middle in the page)

 

- in Kodi disable before the beta installation the  Ziggo addon

- in kodi then choose “install from zipfile”  the  downloaded zipfile.

 

Do it.

 

 

 

Van: pontedennis [mailto:notifications@github.com] 
Verzonden: Sunday, December 27, 2020 2:48 PM
Aan: dut-iptv/dut-iptv.github.io
CC: tke-tke; Author
Onderwerp: Re: [dut-iptv/dut-iptv.github.io] Ziggo GO - Unexpected Error: MissingSchema, not able to log in (#51)

 

How to get the Beta Version 0.9.115?Verzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: tke-tke <notifications@github.com> Datum: 27-12-2020 14:28 (GMT+01:00) Aan: "dut-iptv/dut-iptv.github.io" <dut-iptv.github.io@noreply.github.com> Cc: pontedennis <pontedennis@gmail.com>, Comment <comment@noreply.github.com> Onderwerp: Re: [dut-iptv/dut-iptv.github.io] Ziggo GO - Unexpected Error: MissingSchema, not able to log in (#51) 

Beta Version 0.9.115 seems to be ok







Van: pontedennis [mailto:notifications@github.com] 

Verzonden: Sunday, December 27, 2020 10:01 AM

Aan: dut-iptv/dut-iptv.github.io

CC: tke-tke; Author

Onderwerp: Re: [dut-iptv/dut-iptv.github.io] Ziggo GO - Unexpected Error: MissingSchema, not able to log in (#51)







Yes i have the same problem

**Comment by pontedennis** [comment] 2020-12-27 15:21
ThxVerzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: tke-tke <notifications@github.com> Datum: 27-12-2020  16:17  (GMT+01:00) Aan: "dut-iptv/dut-iptv.github.io" <dut-iptv.github.io@noreply.github.com> Cc: pontedennis <pontedennis@gmail.com>, Comment <comment@noreply.github.com> Onderwerp: Re: [dut-iptv/dut-iptv.github.io] Ziggo GO  - Unexpected Error: MissingSchema, not able to log in (#51) 

 



Goto



https://github.com/bluhb/dut-iptv.github.io/blob/master/beta/leia/plugin.video.ziggo/plugin.video.ziggo-0.9.115.zip



 



and choose button ->download ( about middle in the page)



 



- in Kodi disable before the beta installation the  Ziggo addon



- in kodi then choose “install from zipfile”  the  downloaded zipfile.



 



Do it.



 



 



 



Van: pontedennis [mailto:notifications@github.com] 

Verzonden: Sunday, December 27, 2020 2:48 PM

Aan: dut-iptv/dut-iptv.github.io

CC: tke-tke; Author

Onderwerp: Re: [dut-iptv/dut-iptv.github.io] Ziggo GO - Unexpected Error: MissingSchema, not able to log in (#51)



 



How to get the Beta Version 0.9.115?Verzonden vanaf mijn Galaxy

-------- Oorspronkelijk bericht --------Van: tke-tke <notifications@github.com> Datum: 27-12-2020 14:28 (GMT+01:00) Aan: "dut-iptv/dut-iptv.github.io" <dut-iptv.github.io@noreply.github.com> Cc: pontedennis <pontedennis@gmail.com>, Comment <comment@noreply.github.com> Onderwerp: Re: [dut-iptv/dut-iptv.github.io] Ziggo GO - Unexpected Error: MissingSchema, not able to log in (#51) 



Beta Version 0.9.115 seems to be ok















Van: pontedennis [mailto:notifications@github.com] 



Verzonden: Sunday, December 27, 2020 10:01 AM



Aan: dut-iptv/dut-iptv.github.io



CC: tke-tke; Author



Onderwerp: Re: [dut-iptv/dut-iptv.github.io] Ziggo GO - Unexpected Error: MissingSchema, not able to log in (#51)















Yes i have the same problem

**Comment by dut-iptv** [comment] 2021-01-02 20:54
Will be fixed in 117

**Comment by dut-iptv** [comment] 2021-01-10 21:22
This bug was reproduced and fixed in 0.9.122 which is currently available in the beta repository.

0.9.122 will probably be available in the main repository in a couple of days.

**Comment by dut-iptv** [comment] 2021-01-12 14:11
0.9.128 is available in the main repo and should fix this issue.

If you still encounter this or any other bug please post in #59.

Closing.

**Closed by dut-iptv** 2021-01-12 14:11 UTC
Labels: Ziggo, bug
