### ISSUE TITLE
Error when click login Tv anywhere 

### ISSUE THREAD

**Issue by kersvanbinsbergen** [dut-iptv/dut-iptv.github.io#18] opened 2020-10-03 20:24 UTC
Hi,

Thanks for your effort.

For your information:

Using mibox s 

TV anywhere gives me  this error when i click on login

![16017566472911243851232132746355](https://user-images.githubusercontent.com/35664088/95001104-31f98900-05c7-11eb-9b1b-b2d5b5e97ca1.jpg)

**Comment by dut-iptv** [comment] 2020-10-05 20:17
Duplicate of #14

**Closed by dut-iptv** 2020-10-05 20:17 UTC
