### ISSUE TITLE
[T-mobile Anywhere] _devicekey' referenced before assignment (OSMC)

### ISSUE THREAD

**Issue by Alootje** [dut-iptv/dut-iptv.github.io#15] opened 2020-10-02 19:44 UTC
Installed on RPi3 with OSMC. Had some issues, apparently related to Cryptodome. Installed cryptodome:
```
sudo apt-get install python-crypto
sudo apt-get install build-essential python-pip
sudo pip install -U setuptools
sudo pip install wheel
sudo pip install pycryptodomex
```

No I'm able to open the T-Mobile Anywhere addon. When I click login the following error(s) appear:

ERROR: plugin.video.tmobile - **local variable '_devicekey' referenced before assignment**
Traceback (most recent call last):
File "/home/osmc/.kodi/addons/plugin.video.tmobile/resources/lib/base/signals.py", line 29, in throwable yieldFile "/home/osmc/.kodi/addons/plugin.video.tmobile/resources/lib/base/router.py", line 94, in dispatch function(**params)
File "/home/osmc/.kodi/addons/plugin.video.tmobile/resources/lib/base/plugin.py", line 44, in decorated_function item = f(*args, **kwargs)File "/home/osmc/.kodi/addons/plugin.video.tmobile/resources/lib/plugin.py", line 72, in login if len(_devicekey) == 0:
UnboundLocalError: local variable '_devicekey' referenced before assignment

I tried to "hack" my username + password in /home/osmc/.kodi/addons/plugin.video.tmobile/resources/lib/api.py however this didn't work. :)

Any idea how to solve this error?

Edit: just installed the addon in Kodi on a Windows 10 machine, same error. Maybe I'm missing something..?

**Comment by dut-iptv** [comment] 2020-10-05 20:11
Duplicate of #14 

Bug introduced in recent update, plugins undergoing major rewrite, will be fixed in a short while

**Closed by dut-iptv** 2020-10-05 20:11 UTC
