### ISSUE TITLE
[NLZIET] Epg.db series table is empty. 

### ISSUE THREAD

**Issue by nazegnl** [dut-iptv/dut-iptv.github.io#28] opened 2020-10-25 20:31 UTC
Seems that the pre-aggregated data file the addon is downloading is missing the series data.

**Comment by dut-iptv** [comment] 2020-10-26 08:19
I was not able to reproduce your issue. 
The currently available Epg.db includes the expected data in the series table.

Could be a fluke because of server/connection issues at/with NLZiet maybe?
If these occur while my server is creating the series table it could possibly end up empty.
Some changes have been made server side to prevent connection/server problems resulting in empty Epg tables.

Epg problems are automatically resolved when every 12 hours the data is refreshed (which has already happened).

Closing

**Closed by dut-iptv** 2020-10-26 08:19 UTC
