### ISSUE TITLE
[Ziggo] Not able to watch movies and series

### ISSUE THREAD

**Issue by powermarcel10** [dut-iptv/dut-iptv.github.io#34] opened 2020-10-29 18:43 UTC
Hi and thanks for this great addon! 

When I'm trying to enter the movies or series section, actually every section without live TV I'm getting a strange error:

![16039969628937780806993077925551](https://user-images.githubusercontent.com/2340835/97618147-f8c60480-1a1e-11eb-918b-240066908d42.jpg)

I'm using Windows 10 and kodi 18.9 64-bit.

If you need any further info, please let me know!

**Comment by dut-iptv** [comment] 2020-10-29 21:10
Sorry this error is the result of changes to the EPG/VOD database which was intended to be released along side the latest update to the ziggo addon. Because of circumstances this update was delayed and won't be released until tomorrow.

**Comment by powermarcel10** [comment] 2020-10-29 22:40
Thanks for the confirmation! No problem, take your time.

Cheers

**Comment by dut-iptv** [comment] 2020-10-30 09:15
Should be fixed in .110 which was just pushed to the repo

**Comment by powermarcel10** [comment] 2020-10-30 10:51
Great! Thanks. Kodi does not find any updates yet. Will it take some time?

**Comment by powermarcel10** [comment] 2020-10-30 11:07
I have downloaded the beta repo. It still tells me that the addon has version number 0.9 but it is working now,. Thanks!

**Comment by dut-iptv** [comment] 2020-10-30 11:08
In the future you can force kodi to check for updates:
https://www.matthuisman.nz/2019/09/how-to-force-kodi-to-update-add-ons.html

Good to hear the bug is fixed. Closing

**Closed by dut-iptv** 2020-10-30 11:08 UTC
Labels: Ziggo, bug

**Comment by powermarcel10** [comment] 2020-10-30 11:32
Yeah I did the search for updates, but nothing found. Is it right that the version number now still shows 0.9?

**Comment by dut-iptv** [comment] 2020-10-31 12:43
Version number should show 0.9.114 (or higher when you're reading this)
If not please update manually once from the regular repo

**Comment by powermarcel10** [comment] 2020-10-31 19:21
Yes that's right! Thanks.
