### ISSUE TITLE
[NlZiet] Films and Series next page not working and not sorted

### ISSUE THREAD

**Issue by jbouwh** [dut-iptv/dut-iptv.github.io#37] opened 2020-10-30 16:50 UTC
When using next page at the nlziet the Series or Films submenu the list is not sorted.
Using next page still shows the same list.

**Comment by dut-iptv** [comment] 2020-10-30 23:55
Sorry for the regression. 

Background is that I'm trying to create a 90% (was probably 70%) common code base for all addons with a very small amount of unique code per addon concentrated in only 2 python files which makes bug fixes and enhancements much easier to implement in all addons. It also makes it easier to add more providers (Videoland for instance) in the near future.

Problem is that I'm dealing with 5 very different providers with very different options/capabilities which is causing some growing pains.

Will try to fix asap

**Comment by dut-iptv** [comment] 2020-10-31 08:30
Next page is fixed in .114

Order for items the following menu's is based on the order that NLZiet decides and match the order on the NLZiet website:

-Recommended/Aanbevolen
-Watchahead/Vooruitkijken
-Movies/Films
-Series
-Most watched/Meest bekeken

There is no obvious way to change this order and because the list is retrieved from NLZiet in parts on demand sorting it on the client would give undesirable results.

**Closed by dut-iptv** 2020-10-31 08:30 UTC
Labels: Nlziet, bug
